### ISSUE TITLE
Suggestion - Faction GPS improvement/implementation

### ISSUE THREAD

**Issue by cyberze** [mkaito/SE-GPS-Helper#1]
So there is this faction GPS in sourcecode but it does nothing as far as i can see.

My suggestion is to implement a diffrent approach, mainly on start (UpdateBeforeSimulation) to connect to a predefined (config) repository address (could be  somethign like pastebin*), download a list of GPS coords, import comparing with what one has already, delete old content, and export them back after merge. Same approach to happen each time one adds a new GPS coord. This would comprehensively make faction GPS viable, it would need one repository, and using a configurable adress would make it easy to change if need.

*easily accessible api can be found here https://github.com/gisellevonbingen/PastebinAPIs

**Comment by mkaito** [comment]
While interesting, this is definitely out of scope for this mod.
